#!/bin/sh
set -e
cd "$SRCDIR"
mkdir -p "$DESTDIR/usr/lib"
mkdir -p "$DESTDIR/usr/bin"
make PREFIX="$DESTDIR/usr" install
cp -a libbz2.so.* "$DESTDIR/usr/lib"
ln -s libbz2.so.1.0.8 "$DESTDIR/usr/lib/libbz2.so"
cp bzip2-shared "$DESTDIR/usr/bin/bzip2"
ln -sf bzip2 "$DESTDIR/usr/bin/bzcat"
ln -sf bzip2 "$DESTDIR/usr/bin/bunzip2"
rm -fv "$DESTDIR/usr/lib/libbz2.a"
