#!/bin/sh
set -e
cd "$SRCDIR"
make install || log_error "Destdir is: $DESTDIR"
# Fix a hardcoded path to the executable loader in the ldd script
sed '/RTLDLIST=/s@/usr@@g' -i "$DESTDIR/usr/bin/ldd"
mkdir -p "$DESTDIR/etc"
cat > "$DESTDIR/etc/nsswitch.conf" << "EOF"
# Begin /etc/nsswitch.conf
passwd: files systemd
group: files systemd
shadow: files systemd
hosts: mymachines resolve [!UNAVAIL=return] files myhostname dns
networks: files
protocols: files
services: files
ethers: files
rpc: files
# End /etc/nsswitch.conf
EOF
cat > "$DESTDIR/etc/ld.so.conf" << "EOF"
# Begin /etc/ld.so.conf
/usr/local/lib
/opt/lib
EOF
