#!/bin/sh
set -e
cd "$SRCDIR"
make BUILD_OPT=1                       \
    NSPR_INCLUDE_DIR=/usr/include/nspr \
    USE_SYSTEM_ZLIB=1                  \
    ZLIB_LIBS=-lz                      \
    NSS_ENABLE_WERROR=0                \
    USE_64=1                           \
    "$([ -f /usr/include/sqlite3.h ] && echo NSS_USE_SYSTEM_SQLITE=1)"
