#!/bin/sh
set -e
cd "$SRCDIR"
make install
# So we can remove debugging symbols later
chmod 644 "$DESTDIR/usr/lib/libtclstub8.6.a"
chmod -v u+w "$DESTDIR/usr/lib/libtcl8.6.so"
make install-private-headers
ln -sfv tclsh8.6 "$DESTDIR/usr/bin/tclsh"
# Conflicts with some perl docs
mv "$DESTDIR/usr/share/man/man3/Thread.3" "$DESTDIR/usr/share/man/man3/Tcl_Thread.3"
