#!/bin/sh
set -e
cd "$SRCDIR"
mkdir -p "$DESTDIR/usr/bin"
command install -vm755 ninja "$DESTDIR/usr/bin/"
command install -vDm644 misc/bash-completion "$DESTDIR/usr/share/bash-completion/completions/ninja"
command install -vDm644 misc/zsh-completion  "$DESTDIR/usr/share/zsh/site-functions/_ninja"
