#!/bin/sh
set -e
cd "$SRCDIR"
pip3 install --no-index --find-links dist --root "$DESTDIR" meson
command install -vDm644 data/shell-completions/bash/meson "$DESTDIR/usr/share/bash-completion/completions/meson"
command install -vDm644 data/shell-completions/zsh/_meson "$DESTDIR/usr/share/zsh/site-functions/_meson"
