#!/bin/sh
set -e
cd "$SRCDIR"
make install
mkdir -p "$DESTDIR/usr/bin"
mkdir -p "$DESTDIR/usr/share/man/man1"
install -v -m755 contrib/ssh-copy-id "$DESTDIR/usr/bin"
install -v -m644 contrib/ssh-copy-id.1 "$DESTDIR/usr/share/man/man1"
install -v -m755 -d "$DESTDIR/usr/share/doc/openssh-10.0p1"
install -v -m644 INSTALL LICENCE OVERVIEW README* "$DESTDIR/usr/share/doc/openssh-10.0p1"
