#!/bin/sh
set -e
cd "$SRCDIR"
make install
ln -svr gcc "$DESTDIR/usr/bin/cc"
ln -sv gcc.1 "$DESTDIR/usr/share/man/man1/cc.1"
ln -sfv ../../libexec/gcc/"$(gcc -dumpmachine)"/15.2.0/liblto_plugin.so "$DESTDIR/usr/lib/bfd-plugins/"
ulimit -s -H unlimited
