#!/bin/sh
set -e
cd "$SRCDIR"
make install
mkdir -pv "$DESTDIR/usr/share/applications"
cp -v *.desktop "$DESTDIR/usr/share/applications/"
mkdir -pv "$DESTDIR/etc/X11/app-defaults/"
cat >> /etc/X11/app-defaults/XTerm <<- "EOF"
		*VT100*locale: true
		*VT100*faceName: Monospace
		*VT100*faceSize: 10
		*backarrowKeyIsErase: true
		*ptyInitialErase: true
	EOF
