#!/bin/sh
set -e
cd "$SRCDIR"
make install
mv -v "$DESTDIR/usr/bin/chroot" "$DESTDIR/usr/sbin"
mkdir -pv "$DESTDIR/usr/share/man/man8"
mv -v "$DESTDIR/usr/share/man/man1/chroot.1" "$DESTDIR/usr/share/man/man8/chroot.8"
sed -i 's/"1"/"8"/' "$DESTDIR/usr/share/man/man8/chroot.8"
