#!/bin/sh
set -e
cd "$SRCDIR"
./x.py install
rm -fv "$DESTDIR/opt/rustc-1.89.0/share/doc/rustc-1.89.0/*.old"
install -vm644 README.md "$DESTDIR/opt/rustc-1.89.0/share/doc/rustc-1.89.0"
install -vdm755 "$DESTDIR/usr/share/zsh/site-functions"
ln -sfv /opt/rustc/share/zsh/site-functions/_cargo "$DESTDIR/usr/share/zsh/site-functions"
mkdir -pv "$DESTDIR/usr/share/bash-completion/completions"
mv -v "$DESTDIR/etc/bash_completion.d/cargo" "$DESTDIR/usr/share/bash-completion/completions"
mkdir -pv "$DESTDIR/etc/profile.d/"
cp -av "$PKGROOT/70-rustc-in-path.sh" "$DESTDIR/etc/profile.d/"
